--- #YAML:1.0
name:                JSON-DWIW
version:             0.23
abstract:            JSON converter that does what I want
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - DON OWENS <don@regexguy.com>
