--- #YAML:1.0
name:               JSON-DWIW
version:            0.29
abstract:           JSON converter that does what I want
author:
    - DON OWENS <don@regexguy.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
